Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port",guest:80,host:8000
  config.vm.synced_folder "html" ,"/var/web"
  config.vm.provision "shell", inline: <<-SHELL
    echo "aprovisionant"
    sudo apt-get update > /dev/null
    sudo apt-get install -y apache2 > /dev/null
    sudo ln -fs /var/web /var/www
SHELL
end
