Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest:80, host:8000
  config.vm.synced_folder "html" ,"/var/web"
  config.vm.provision :shell do |script|
    script.path = "bootstrap.sh"
  end
end
